// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  profileSidebar: [
    {
      type: 'category',
      label: 'Profile',
      items: [
        { type: 'doc', id: 'intro', label: 'About Me' },
        { type: 'doc', id: 'contact-me', label: 'Contact Me' },
      ],
    },
  ],

  writetechSidebar: [
    { type: 'doc', id: 'writetech-portfolio/writetech-intro', label: 'Overview' },

    {
      type: 'category',
      label: 'Documentation Tooling',
      items: [
        'writetech-portfolio/documentation-tooling/intro',
        'writetech-portfolio/documentation-tooling/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'writetech-portfolio/documentation-tooling/api-reference/get-user',
            'writetech-portfolio/documentation-tooling/api-reference/post-transaction',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'API Documentation and OpenAPI',
      items: [
        'writetech-portfolio/api-documentation-and-openapi/intro',
        'writetech-portfolio/api-documentation-and-openapi/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'writetech-portfolio/api-documentation-and-openapi/reference/add-beneficiary',
            'writetech-portfolio/api-documentation-and-openapi/reference/wallet-details',
            'writetech-portfolio/api-documentation-and-openapi/referencewallet-transfer-quotes',
            'writetech-portfolio/api-documentation-and-openapi/referencewallet-transfer'
          ]      
        }
      ]
    },
    {
      type: 'category',
      label: 'Documentation Automation',
      items: ['writetech-portfolio/documentation-automation/intro']
    },
    {
      type: 'category',
      label: 'AI for Documentation',
      items: ['writetech-portfolio/ai-for-docs/intro']
    },
    {
      type: 'category',
      label: 'DevOps & Cloud Documentation',
      items: ['writetech-portfolio/devops-and-cloud-docs/intro']
    },
    {
      type: 'category',
      label: 'Technical Writing in Web3',
      items: ['writetech-portfolio/web3-documentation/intro']
    },
  ],

  freelanceSidebar: [
    {
      type: 'doc',
      id: 'freelance-work/freelance-intro',
      label: 'Overview',
    },
  ],
  
};

export default sidebars;
